### PR TITLE
Textures + heat def fix

### PR DESCRIPTION
**Pull request by Coach-mdl**
Did a bit of switcheroo. I replaced leather_flask_1's texture with leather_flask_2 and then made a new texture for the new flask 2. The reason I did this is because there was no size difference between flask 1 and flask 0. The only distinction from the two was that flask 0 was open and flask 1 was closed. I also did this because there weren't many pixels to work with in flask 1 to get it in between 20-40% full and not look nearly identical to the old flask 2. On an unrelated note, I gave the unfinished iron flask it's heat definition which can be found at src/main/resources/data/waterflasks/tfc/item_heats. Hopefully it works. It should but don't put it past me to have a typo somewhere.

### CODE REVIEW

**Comment by Gaelmare** [comment]
Thanks! So I pushed an update that moved these around to match the actual usage, but I see one new tier of fullness in these new textures that will work.

This is how they map:
100% full: leather_flask.png
80% full: leather_flask-4.png
60% full: leather_flask-3.png
40% full: leather_flask-2.png
20% full: leather_flask-1.png
0% full: leather_flask-0.png

**Comment by Gaelmare** [comment]
Ah, I also need to make similar changes for the iron flask textures.

**Comment by Coach-mdl** [comment]
The thrilling task of renaming everything. I take it you don't need me to rename them right?

**Comment by Gaelmare** [comment]
Merged manually, thanks!

**Comment by Gaelmare** [comment]
3.0.4 is waiting for approval CF with these changes,

**Pull request closed without merging**
